public class Issues
{
    /*
     * ........
     * ........
     * ..XXXO..
     * ...XO...
     * ...OX...
     * ........
     * ........
     * ........
     * Please enter the row number where you would like to place your piece.
     * 3
     * Please enter the column number where  you would like to place your piece.
     * 7
     * ........
     * ........
     * ..XXXXX.
     * ...XO...
     * ...OX...
     * ........
     * ........
     * ........
     * 
     * vs. 
     * 
     * ........
     * ........
     * ..XXXXX.
     * ..XXO...
     * ..XOX...
     * ..O.....
     * ........
     * ........
     * Please enter the row number where you would like to place your piece.
     * 4
     * Please enter the column number where  you would like to place your piece.
     * 6
     * ........
     * ........
     * ..XXXXX.
     * ..XXOX..
     * ..XOX...
     * ..O.....
     * ........
     * ........
     */
}